#!/bin/bash

cat <<EOF > README.md
# texttospeech

## INSTALL

$(./install | sed 's/^/    /')

## USAGE

$(./texttospeech | sed 's/^/    /')

## SETUP GIT

    # setup_git content
$(cat setup_git | sed 's/^/    /')

## LICENSE

$(cat LICENSE)
EOF