#!/bin/bash

cat <<EOF > README.md
# texttospeech

## PREREQUISITES

* ffplay installed
* ~/.local folder wired properly (tested on Ubuntu 18.04)

## INSTALL

$(./install | sed 's/^/    /')

## USAGE

$(./texttospeech | sed 's/^/    /')

## SETUP GIT

    ./setup_git

    # setup_git content:
$(cat setup_git | sed 's/^/    /')

## LICENSE

$(cat LICENSE)
EOF