#!/bin/bash
set -eo pipefail

if [[ "$1" != "--install" ]]; then
  cat <<EOF
usage: ./install --install [google_cloud_key_json_file]

Arguments
  google_cloud_key_json_file  google cloud json file path
                              (optional if already installed)
EOF
  exit
fi

shift

if [[ ! -f "$1" ]] && [[ ! -f ~/.local/var/texttospeech/avymtsw0i5.json ]]; then
  echo "Must provide valid path for GOOGLE_APPLICATION_CREDENTIALS file" >&2
  exit 1
fi

mkdir -p ~/.local/bin
cp -f "$PWD/texttospeech" ~/.local/bin/texttospeech

mkdir -p ~/.local/var/texttospeech

if [[ -n $1 ]]
	then cp "$1" ~/.local/var/texttospeech/avymtsw0i5.json
fi

echo "texttospeech installed successfully"
