#!/bin/bash
set -eo pipefail

if [ -z "$1" ]; then
  cat <<EOF
usage: ./install <google_cloud_key_json_file>
EOF
  exit
fi

if [ ! -f "$1" ]; then
  echo "Must provide valid path for GOOGLE_APPLICATION_CREDENTIALS file" >&2
  exit 1
fi

mkdir -p ~/.local/bin
ln -sf "$PWD/texttospeech" ~/.local/bin/texttospeech

mkdir -p ~/.local/var/texttospeech
cp "$1" ~/.local/var/texttospeech/avymtsw0i5.json

echo "texttospeech installed successfully"